name: update backend deployment
on:
  push:
    branches:
      - master

# Let's do this via a docker container in the future, this is pretty bad.
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: update deployment
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: fuser -k 3000/tcp & cd wg-app/backend && ~/.local/share/pnpm/pnpm i && ~/.local/share/pnpm/pnpm build && ~/.local/share/pnpm/pnpm start:prod
