name: (re)-deploy backend

on:
  push:
    branches:
      - master

# Let's do this via a docker container in the future, this is pretty ugly.
jobs:
  deploy:
    name: (Re)-Deploy backend
    runs-on: ubuntu-latest
    steps:
    - name: update deployment
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEPLOY_SSH_HOST }}
        username: ${{ secrets.DEPLOY_SSH_USERNAME }}
        password: ${{ secrets.DEPLOY_SSH_PASSWORD }}
        port: ${{ secrets.PORT }}
        # TODO: lets move the cd into working-directory
        script: |
          cd ${{ secrets.DEPLOY_SSH_REPO_DIRECTORY}}
          git pull
          cd backend/
          pnpm i
          pnpm build
          pnpm start:prod
