name: (re)-deploy backend

on:
  push:
    branches:
      - master
  pull_request:

# Let's do this via a docker container in the future, this is pretty ugly.
jobs:
  deploy:
    name: (Re)-Deploy backend
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@master
      - name: install cloudflared
        run: |
          curl -L https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-archive-keyring.gpg >/dev/null
          echo "deb [signed-by=/usr/share/keyrings/cloudflare-archive-keyring.gpg] https://pkg.cloudflare.com/cloudflared $(lsb_release -cs) main" | sudo tee  /etc/apt/sources.list.d/cloudflared.list
          sudo apt update
          sudo apt-get install cloudflared
          cloudflared --version
      - name: install-ssh-key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail
      - name: deploy backend
        run:
          ssh -i ~/.ssh/id_rsa -o ProxyCommand="cloudflared access ssh --hostname ssh.invertedecho.com" -o StrictHostKeyChecking=no echo@ssh.invertedecho.com < ./scripts/deploy_backend.sh
